services:
  _defaults:
    public: true

  react.redis:
    class: Morbo\React\Redis\Service\Redis
    arguments: ["@service_container", "@react.loop"]

  Morbo\React\Redis\Service\Redis: '@react.redis'